### ISSUE TITLE
Add option to tag a public version based on calculated nbgv version

### ISSUE THREAD

**Issue by japj** [AArnott/nbgv#21]
e.g. to ensure a published package has a corresponding git tag

(although you could also use the nbgv tool to match a version to a commit ofcourse)

**Comment by AArnott** [comment]
Are you wanting nbgv to create a git tag and push it to your repo? 
Under what conditions would it do that? Or do you want every "public release" commit that is ever built to have a tag pushed for it?

**Comment by japj** [comment]
Sorry, I am not entirely sure anymore ;(

I was/am working on a native nodejs library with github actions workflow for prebuilding binaries.
And prebuild can create a github release in case it’s not there yet, but I believe that is based on the tag.
I think this might a think over again on how my complete (publishing) workflow should be in the end.

Should have put more background info in here for myself to correctly remember

**Comment by AArnott** [comment]
If your workflow creates a github release, that *can* identify the commit in the release itself. Then, if you ever *publish* that release, github automatically pushes a tag to your repo based on that commit and the name of the release.
This is actually how I release _all_ my software. I create the github release from an Azure Pipeline as a 'draft' release, and I publish manually after I review the release notes.
