### ISSUE TITLE
Regarding nbgv.json

### ISSUE THREAD

**Issue by AArnott** [AArnott/nbgv#3]
Why does the action produce a nbgv.json file? 
Is the root directory of the user's source tree the right place to create such a file, or does GitHub Actions define an artifacts directory that would be more appropriate?

**Comment by ctaggart** [comment]
nbgv.json is not needed. I recommend removing it:
https://github.com/AArnott/nbgv/blob/10e1135ef1d89a3db40c2eb571794f981411c326/src/main.ts#L28-L34

I'm not that familiar with `nbgv cloud --all-vars`, but if it is for setting the cloud variables, may be we should try setting them with it. The format is `##[set-env name=NBGV_SemVer2;]0.7.17-ga79541b`. I'll try echoing that format to verify that it works. You could then avoid creating and reading the json and switch the command.

**Comment by AArnott** [comment]
Already done here: https://github.com/AArnott/Nerdbank.GitVersioning/pull/378

I'd appreciate you testing it though!

**Comment by ctaggart** [comment]
Yes, just echoing that to stdout works.

``` yaml
    - run: echo "##[set-env name=NBGV_SemVer2;]0.7.17-ga79541b"
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
```

https://github.com/ctaggart/froto/runs/196810208
![image](https://user-images.githubusercontent.com/80104/63250352-079f1c00-c29e-11e9-9f68-7e6195636801.png)

If you want me to test a beta build, you can add `version` and `source` input options to pass in here if set: 
https://github.com/AArnott/nbgv/blob/10e1135ef1d89a3db40c2eb571794f981411c326/src/main.ts#L10
