### ISSUE TITLE
Add option to stamp package.json with nbgv version

### ISSUE THREAD

**Issue by AArnott** [AArnott/nbgv#6]

**Comment by japj** [comment]
Do you have an idea yet how the gitihub action api should look for this?

I am not familiar with writing github actions, but I recently started working on a "hobby" project that I would like to use this on. So if I can help implement this please let me know

**Comment by AArnott** [comment]
Maybe all we need to do is document how to do it. I do it here:

https://github.com/AArnott/cloudbuild-task/blob/928bbf0706fbaa5f296c0d3177df569d882e1f3d/.github/workflows/build.yml#L45-L48

Building it into this github action as a standalone feature could work too. I'm not yet sure exactly how I would expose it. Perhaps a `packageJson` input that is the path to the package.json file to be changed.
