### ISSUE TITLE
Are actions not running on this repo itself?

### ISSUE THREAD

**Issue by AArnott** [AArnott/nbgv#7]
@ctaggart: I'm finally in the github actions v2 preview. I pushed to this repo, but the action you defined for this repo did not run. Any ideas why?

**Comment by ctaggart** [comment]
I see there is an action defined:
https://github.com/AArnott/nbgv/blob/master/.github/workflows/checkin.yml

Are they enabled in project settings?
![image](https://user-images.githubusercontent.com/80104/64410833-2bc76f00-d08c-11e9-8fd4-dbc61c28f4e7.png)

**Comment by AArnott** [comment]
Yes

**Comment by AArnott** [comment]
I got it working.
